name: Main Workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '14', '16' ]
    name: Compile, test and build - Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm install
      - run: npm run compile
      - run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy on Goerli
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: npm
      - run: npm install
      - run: npm run compile
      - run: npm run goerli:deploy
        env:
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          GOERLI_MNEMONIC: ${{ secrets.GOERLI_MNEMONIC }}
        